language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

env:
  - BOARD=uno
  - BOARD=mzeropro
  - BOARD=zero

script:
  - make ci

before_deploy:
  - export RELEASE_VERSION=$TRAVIS_TAG
  - export RELEASE_ZIP=Helium-$RELEASE_VERSION.zip
  - export RELEASE_DIR=$TRAVIS_BUILD_DIR
  - make release

after_deploy:
  - make gh-pages

deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    api_key:
    secure: IYHaNb9hbgDKXbRpEAUp6hNwQbyETRPHeLn+7c01nyrMm2kxK6IhetiHena6hK5qDzjI++xcu4glXLO4w87vpYZUryTImYX75M5Djau7b3nddWTkTe+OVx0VG6DXB9ahajPjNSDyQI8Ma5OwnTRRsjnEePVU96IvY9XCQKKnEik/KmX/WqgwDWdu95SSgzSKFF+tm2MM44x4wxUg3SW2a2ZEkGs74gi2HElV2KnxQ3NkKLmXGVHM/i89gUhuw/nMrhzR1m1ZV6X71AqiQAdV1UxlCM/MyX6apIkIQJH3JOJokFg9wHBmmTVMg5A8jCdf4OiGm8oY7NHfJUqFz2gWrv3QHKq51CWFPdSftWahBLVxgsHEhZA0I5tsfNp1BL9zNUjVa10NeMgao9iSVx4dNC23s/jj6Po4Bc/tU/HGlGT8GJsgGAQGVFAg1Ek1Mp1Y4GYXA6M47cJez61fH+wbZ2OEtx/B3lmNseNd5/Ebfe82P9AayfNGzLCkAeuhf7XzcltBqwt2NHvMOPWPqsA1plNzrwKpIrWy4ItRw23H5UJ6ErUGluwJWNiS+YUVN+5z83RadnJyd3k/Lgn/+UaXRZT7J6F1FJ3hRA+qLIvXxYpytYfrLLidCc8YPIyEuLuc8jalb1VNex5lGfzZ1m6cPH2dP6a/lNf7R7GQHhfot9A=
    file: "${RELEASE_ZIP}"
    on:
      repo: helium/helium-arduino
      tags: true
      condition: $BOARD = uno
