language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

env:
  - BOARD=uno
  - BOARD=mzeropro
  - BOARD=zero

script:
  - make ci

before_deploy:
  - export RELEASE_VERSION=$TRAVIS_TAG
  - export RELEASE_ZIP=Helium-$RELEASE_VERSION.zip
  - export RELEASE_DIR=$TRAVIS_BUILD_DIR
  - make release

after_deploy:
  - make gh-pages

deploy:
  - provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: FJGNmnkGItMpvYe9DEEd5CfAgu9JRZ/B6A+0NkveIbK7VBpkgGllqXnzaoNcfu/rD6wh31AQNKhUAv5Uu08Ze4fMjb585jLVCi7Q9g3hVk3bIqYeMEGlwO379R1qdq9G9W0cBBylYFGNd//97UHJlbNp96nW7Eq4sm7i4EJeJzVsdmGtahSUbiChvVpP32DT2ayVp2CPQi0GlwZPg2oldbMPP2G9bsaIokCfTvaYPOzfjNreeYe8dV2YeXr6ycj6Zq9qu4b7UKpWv3oB+6y9pBAJRCpQ3F0iD3Jr9KFHKlr/+wU6+h6ZUiXHOLifmOhXRcP50ZK9g/GceuiyN3OHAgqWJ8BVTdcxsiGttrL1bMiSJI6OL/TFFU21yWvHx3pxetXoW9uS1Krs096I5WDZUzsgPdveYb73mLQ4QCSY1RMlxFvfFtMiSYR9lcnDAZVLTJiCwaHjSc2PvQGi1w64Tz5507giNJ1xl07MNTc5DolTO2+Ojugjk1MUa/gTuxCUMglVE+xxMn1c+i8Ex00LMUvOE2U6sIcatrGtwCbuFS3VENOwg99NSPCjdCh4uwqCjo8DL3c5gTEgRWTbsfTPVjU4LR6ovk3TczdkJlYKssEQmnJEo+7JHzfAWJlf1XDtcIanx5RxpW2EHcqa9iCpdUXZcn18/5Pgkh0LuIZJ/bU=
    file: "${RELEASE_ZIP}"
    on:
      repo: helium/helium-arduino
      tags: true
      condition: $BOARD = uno
