language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

env:
  - BOARD=uno
  - BOARD=mzeropro
  - BOARD=zero
  - BOARD=due

script:
  - make ci

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - make gh-pages
    on:
      repo: helium/helium-arduino
      tags: true
      condition: $BOARD = uno
