language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

env:
  - BOARD=uno
  - BOARD=mzeropro
  - BOARD=zero

script:
  - make ci

before_deploy:
  - export RELEASE_VERSION=$TRAVIS_TAG
  - export RELEASE_ZIP=Helium-$RELEASE_VERSION.zip
  - export RELEASE_DIR=$TRAVIS_BUILD_DIR
  - make release

after_deploy:
  - make gh-pages

deploy:
  - provider: releases
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: RQ01h7Dq9xYXk9sJAl5scBJ2VQPiDdzrU0UIY2FApwSx6Lrx/s3OiraJ5MmSE+17sRB0RThJpUVJunaIWgL5C5aIz7RWQ8QY1e8PAajjKmWD+GI/RpeDMfkJOTx4ZCZPmAB1cghpWlmJiwrfsNOmRXnH/5fZQEaB+7prm03F1t8devp+/ieAogtVeE9aiW2lh7NUCHS6txJr8DVt1UDLWf5riNsWc7b+4plZK4mfVP5g3HpYTkXZOm6BgqnKBh7jClUQStp8ciRShAYH+LmLvCGtWPrFiGPQV+a6Y9ALI/EKjkBwc9kMeNOzgbYFQmmCnusJ3W+PKrURZeMymSNd0CXUqToDYxahygaelnh6iyoMX4yMWlkJuIWKyTsnWAoayOv5jz/hO4y6G3pwrXfbyYFmBWhzOHjuThWMMv8kSjldtj38Dyg8Cs8iPNVTIyvr+0ZZq3V9xd2gtZWmv5o1XzDL2KWOXanOxlE1EyeKhVTWS2fe6083i6sUoSE9DLm24cP6cEDAMmMbauTzn8K7gahZHCjeHv+pFKOWjX7Z82aNntGY/vP0tGvk/wbqueOiZ4FZKl3f0lSaWc4Yhv/FFj3W3QF8BOCAI5jW7/i/xB5tGIcQdYXJI3MM/EReIUA5iU6LGi+U37GWCCh/O2o4dIc78IcCasLi1MIX7qDZrNk=
    file: "${RELEASE_ZIP}"
    on:
      repo: helium/helium-arduino
      tags: true
      condition: $BOARD = uno
