language: python

cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio

env:
  - BOARD=uno
  - BOARD=mzeropro
  - BOARD=zero
  - BOARD=due

script:
  - make ci

after_deploy:
  - make gh-pages

deploy:
  - provider: releases
    on:
      repo: helium/helium-arduino
      tags: true
      condition: $BOARD = uno
